version: '3.2'

services:

  vc_buildserver_app: &app
    tty: true
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: vc_buildserver
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/app:delegated
      - /var/log/:/var/log/
    depends_on:
      - postgres
      - mongodb
    ports:
      - 8080:8080
      - 8081:8081
    command: make adev

  postgres:
      image: postgres:10
      container_name: vc_buildserver_postgres
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      ports:
          - 5432

  mongodb:
      image: 'mongo:latest'
      container_name: vc_buildserver_mongodb
      environment:
        - MONGO_DATA_DIR=/usr/local/var/mongodb/
        - MONGO_LOG_DIR=/usr/local/var/log/mongodb
        - MONGO_INITDB_ROOT_USERNAME="vc-user"
        - MONGO_INITDB_ROOT_PASSWORD="logi123"
      volumes:
        - /usr/local/var/mongodb/:/usr/local/var/mongodb/

      ports:
        - 27017:27017


  test:
    <<: *app
    container_name: vc_buildserver_test
    ports:
      - 8082:8082
    entrypoint: py.test -v -p no:warnings
