version: '3.2'

services:

  vc_buildserver_app: &app
    tty: true
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: vc_buildserver
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
      - mongodb
    ports:
      - 8080:8080
      - 8081:8081
    command: make adev

  postgres:
      image: postgres:10
      container_name: vc_buildserver_postgres
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      ports:
          - 5432

  mongodb:
      image: mongo:latest
      container_name: vc_buildserver_mongodb
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
        - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet

  test:
    <<: *app
    container_name: vc_buildserver_test
    ports:
      - 8082:8082
    entrypoint: py.test -v -p no:warnings
