version: '3.2'

services:
  vc_buildserver_app:
    build:
      args:
        requirements: requirements/production.txt
    environment:
      # use in code
      - SETTINGS_FILE=api.prod.yml
    command: python3 -m vc_buildserver
