# app
app:
  host: 0.0.0.0
  port: 9000

# postgres
postgres:
  user: postgres_test
  password: postgres_test
  database: postgres_test
  port: 5432
  host: postgres

# MongoDB
mongodb:
  user: vc-user
  password: logi123
  database: versiondb
  port: 27017
  host: mongodb